[doc] gunicorn: use GeventWebSocketWorker
Fix this issue:

    [ERROR] Error handling request /socket.io/?EIO=3&transport=websocket&sid=2c22a5aa417c4afa9a9acf095271bace
    Traceback (most recent call last):
      File "gunicorn/workers/base_async.py", line 55, in handle
	self.handle_request(listener_name, req, client, addr)
      File "gunicorn/workers/ggevent.py", line 143, in handle_request
	super().handle_request(listener_name, req, sock, addr)
      File "gunicorn/workers/base_async.py", line 106, in handle_request
	respiter = self.wsgi(environ, resp.start_response)
      File "flask/app.py", line 2463, in __call__
	return self.wsgi_app(environ, start_response)
      File "flask_socketio/__init__.py", line 45, in __call__
	return super(_SocketIOMiddleware, self).__call__(environ,
      File "engineio/middleware.py", line 60, in __call__
	return self.engineio_app.handle_request(environ, start_response)
      File "socketio/server.py", line 526, in handle_request
	return self.eio.handle_request(environ, start_response)
      File "engineio/server.py", line 350, in handle_request
	packets = socket.handle_get_request(
      File "engineio/socket.py", line 105, in handle_get_request
	return getattr(self, '_upgrade_' + transport)(environ,
      File "engineio/socket.py", line 146, in _upgrade_websocket
	return ws(environ, start_response)
      File "engineio/async_drivers/gevent.py", line 35, in __call__
	raise RuntimeError('You need to use the gevent-websocket server. '
    RuntimeError: You need to use the gevent-websocket server. See the Deployment section of the documentation for more information.