patch error when reply is None in get_last_notifications()
line 1459 a check is made for 'reply is not None', but the fact is that few lines earlier you are calling reply.get("mentions", []) which will throw an AttributeError when reply == None ('NoneType' object has no attribute 'get')